name = "whatsapp-chat-widget"
client_id = "cbd3b7ab27e913ec1d9cf3bec9cd78ad"
application_url = "https://shopify-whatsapp-app-m6cy.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_themes,read_themes,write_script_tags"

[auth]
redirect_urls = [
  "https://shopify-whatsapp-app-m6cy.onrender.com/auth/callback",
  "https://shopify-whatsapp-app-m6cy.onrender.com/auth/shopify/callback",
  "https://shopify-whatsapp-app-m6cy.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://lalitacyrus.myshopify.com"
